# Generated by Django 2.1.2 on 2018-10-09 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('activated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Activate Bid for Decision Makers')),
                ('closed', models.BooleanField(default=False, verbose_name='Close Bid')),
            ],
            options={
                'permissions': (('admin', 'admin'), ('decision_maker', 'decision_maker')),
            },
        ),
        migrations.CreateModel(
            name='BidResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=50, verbose_name='My Response')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Bid', verbose_name='Bid')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Business name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectType', models.FileField(null=True, upload_to='projectType/', verbose_name='Type of Past Projects Completed')),
                ('projectSize', models.FileField(null=True, upload_to='projectSize/', verbose_name='Size of Past Projects Completed')),
                ('numProject', models.FileField(null=True, upload_to='numProject/', verbose_name='Number of Past Projects Completed')),
                ('localAreaExperience', models.FileField(null=True, upload_to='localAreaExperience/', verbose_name='Experience in Local Area')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor', verbose_name='Choose Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundness', models.FileField(null=True, upload_to='soundness/', verbose_name='Financial Soundness')),
                ('credit_rating', models.FileField(null=True, upload_to='credit_rating', verbose_name='Financial Credit Rating')),
                ('banking_bonding', models.FileField(null=True, upload_to='banking_bonding/', verbose_name='Financial Arrangements and Bonding')),
                ('status', models.FileField(null=True, upload_to='status/', verbose_name='Financial Status')),
                ('liquidity', models.FileField(null=True, upload_to='liquidity/', verbose_name='Financial Liquidity')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor', verbose_name='Choose Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStabilityRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundness_positive', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('1,2,3', 'Equally to Moderately Preferred'), ('2,3,4', 'Moderately Preferred'), ('3,4,5', 'Moderately to Strongly Preferred'), ('4,5,6', 'Strongly Preferred'), ('5,6,7', 'Strongly to Very Strongly Preferred'), ('6,7,8', 'Very Strongly Preferred'), ('7,8,9', 'Very Strongly to Extremely Preferred'), ('8,9,9', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Soundness')),
                ('soundness_reverse', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('0.3333,0.5,1', 'Equally to Moderately Preferred'), ('0.25,0.3333,0.5', 'Moderately Preferred'), ('0.2, 0.25, 0.3333', 'Moderately to Strongly Preferred'), ('0.1667, 0.2, 0.25', 'Strongly Preferred'), ('0.1429, 0.1667, 0.2', 'Strongly to Very Strongly Preferred'), ('0.125, 0.1429, 0.1667', 'Very Strongly Preferred'), ('0.1111, 0.125, 0.1429', 'Very Strongly to Extremely Preferred'), ('0.1111, 0.1111, 0.125', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Soundness - Reverse')),
                ('credit_rating_positive', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('1,2,3', 'Equally to Moderately Preferred'), ('2,3,4', 'Moderately Preferred'), ('3,4,5', 'Moderately to Strongly Preferred'), ('4,5,6', 'Strongly Preferred'), ('5,6,7', 'Strongly to Very Strongly Preferred'), ('6,7,8', 'Very Strongly Preferred'), ('7,8,9', 'Very Strongly to Extremely Preferred'), ('8,9,9', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Credit Rating')),
                ('credit_rating_reverse', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('0.3333,0.5,1', 'Equally to Moderately Preferred'), ('0.25,0.3333,0.5', 'Moderately Preferred'), ('0.2, 0.25, 0.3333', 'Moderately to Strongly Preferred'), ('0.1667, 0.2, 0.25', 'Strongly Preferred'), ('0.1429, 0.1667, 0.2', 'Strongly to Very Strongly Preferred'), ('0.125, 0.1429, 0.1667', 'Very Strongly Preferred'), ('0.1111, 0.125, 0.1429', 'Very Strongly to Extremely Preferred'), ('0.1111, 0.1111, 0.125', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Credit Rating - Reverse')),
                ('banking_bonding_positive', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('1,2,3', 'Equally to Moderately Preferred'), ('2,3,4', 'Moderately Preferred'), ('3,4,5', 'Moderately to Strongly Preferred'), ('4,5,6', 'Strongly Preferred'), ('5,6,7', 'Strongly to Very Strongly Preferred'), ('6,7,8', 'Very Strongly Preferred'), ('7,8,9', 'Very Strongly to Extremely Preferred'), ('8,9,9', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Arrangements and Bonding')),
                ('banking_bonding_reverse', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('0.3333,0.5,1', 'Equally to Moderately Preferred'), ('0.25,0.3333,0.5', 'Moderately Preferred'), ('0.2, 0.25, 0.3333', 'Moderately to Strongly Preferred'), ('0.1667, 0.2, 0.25', 'Strongly Preferred'), ('0.1429, 0.1667, 0.2', 'Strongly to Very Strongly Preferred'), ('0.125, 0.1429, 0.1667', 'Very Strongly Preferred'), ('0.1111, 0.125, 0.1429', 'Very Strongly to Extremely Preferred'), ('0.1111, 0.1111, 0.125', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Arrangements and Bonding - Reverse')),
                ('status_positive', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('1,2,3', 'Equally to Moderately Preferred'), ('2,3,4', 'Moderately Preferred'), ('3,4,5', 'Moderately to Strongly Preferred'), ('4,5,6', 'Strongly Preferred'), ('5,6,7', 'Strongly to Very Strongly Preferred'), ('6,7,8', 'Very Strongly Preferred'), ('7,8,9', 'Very Strongly to Extremely Preferred'), ('8,9,9', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Status')),
                ('status_reverse', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('0.3333,0.5,1', 'Equally to Moderately Preferred'), ('0.25,0.3333,0.5', 'Moderately Preferred'), ('0.2, 0.25, 0.3333', 'Moderately to Strongly Preferred'), ('0.1667, 0.2, 0.25', 'Strongly Preferred'), ('0.1429, 0.1667, 0.2', 'Strongly to Very Strongly Preferred'), ('0.125, 0.1429, 0.1667', 'Very Strongly Preferred'), ('0.1111, 0.125, 0.1429', 'Very Strongly to Extremely Preferred'), ('0.1111, 0.1111, 0.125', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Status - Reverse')),
                ('liquidity_positive', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('1,2,3', 'Equally to Moderately Preferred'), ('2,3,4', 'Moderately Preferred'), ('3,4,5', 'Moderately to Strongly Preferred'), ('4,5,6', 'Strongly Preferred'), ('5,6,7', 'Strongly to Very Strongly Preferred'), ('6,7,8', 'Very Strongly Preferred'), ('7,8,9', 'Very Strongly to Extremely Preferred'), ('8,9,9', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Liquidity')),
                ('liquidity_reverse', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('0.3333,0.5,1', 'Equally to Moderately Preferred'), ('0.25,0.3333,0.5', 'Moderately Preferred'), ('0.2, 0.25, 0.3333', 'Moderately to Strongly Preferred'), ('0.1667, 0.2, 0.25', 'Strongly Preferred'), ('0.1429, 0.1667, 0.2', 'Strongly to Very Strongly Preferred'), ('0.125, 0.1429, 0.1667', 'Very Strongly Preferred'), ('0.1111, 0.125, 0.1429', 'Very Strongly to Extremely Preferred'), ('0.1111, 0.1111, 0.125', 'Extremely Preferred')], max_length=20, null=True, verbose_name='Financial Liquidity - Reverse')),
                ('bid_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.BidResponse')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualityPolicy', models.FileField(null=True, upload_to='qualityPolicy/', verbose_name='Quality Policy')),
                ('projectManagement', models.FileField(null=True, upload_to='projectManagement/', verbose_name='Project Management Organization')),
                ('culture', models.FileField(null=True, upload_to='culture/', verbose_name='Organizational Culture')),
                ('knowledge', models.FileField(null=True, upload_to='knowledge/', verbose_name='Management Knowledge')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor', verbose_name='Choose Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationalHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthSafety', models.FileField(null=True, upload_to='healthSafety/', verbose_name='Health and Safety Performance Report')),
                ('safety', models.FileField(null=True, upload_to='safety/', verbose_name='Occupational Safety and Health Administration Procedures')),
                ('generalAssessment', models.FileField(null=True, upload_to='generalAssessment/', verbose_name='General Assessment of Safety Attitudes')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor', verbose_name='Choose Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='PastPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.FileField(null=True, upload_to='quality/', verbose_name='Quality Level of Project Performance')),
                ('completedTime', models.FileField(null=True, upload_to='completionTime/', verbose_name='Projects Completed on Time')),
                ('completedBudjet', models.FileField(null=True, upload_to='completedBudjet/', verbose_name='Projects Completed on Budget')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor', verbose_name='Choose Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failures', models.FileField(null=True, upload_to='failures/', verbose_name='Past Failures')),
                ('timeInBusiness', models.FileField(null=True, upload_to='timeInBusiness/', verbose_name='Length of time in Business')),
                ('pastOwner', models.FileField(null=True, upload_to='pastOwner/', verbose_name='Past Owner / Contractor Relationship')),
                ('relationships', models.FileField(null=True, upload_to='relationships/', verbose_name='Other Relationships')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor', verbose_name='Choose Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('1,2,3', 'Equally to Moderately Preferred'), ('2,3,4', 'Moderately Preferred'), ('3,4,5', 'Moderately to Strongly Preferred'), ('4,5,6', 'Strongly Preferred'), ('5,6,7', 'Strongly to Very Strongly Preferred'), ('6,7,8', 'Very Strongly Preferred'), ('7,8,9', 'Very Strongly to Extremely Preferred'), ('8,9,9', 'Extremely Preferred')], max_length=20, null=True)),
                ('negative', models.CharField(choices=[('1,1,1', 'Equally Preferred'), ('0.3333,0.5,1', 'Equally to Moderately Preferred'), ('0.25,0.3333,0.5', 'Moderately Preferred'), ('0.2, 0.25, 0.3333', 'Moderately to Strongly Preferred'), ('0.1667, 0.2, 0.25', 'Strongly Preferred'), ('0.1429, 0.1667, 0.2', 'Strongly to Very Strongly Preferred'), ('0.125, 0.1429, 0.1667', 'Very Strongly Preferred'), ('0.1111, 0.125, 0.1429', 'Very Strongly to Extremely Preferred'), ('0.1111, 0.1111, 0.125', 'Extremely Preferred')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalCapability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.FileField(null=True, upload_to='experience/', verbose_name='Experience of Technical Personnels')),
                ('labour', models.FileField(null=True, upload_to='labour/', verbose_name='Labour and Equipment')),
                ('qualification', models.FileField(null=True, upload_to='qualification/', verbose_name='Qualification of Personnels')),
                ('ability', models.FileField(null=True, upload_to='ability/', verbose_name='Ability of Personnels')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor', verbose_name='Choose Contractor')),
            ],
        ),
        migrations.AddField(
            model_name='bidresponse',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahp_app.Contractor'),
        ),
        migrations.AddField(
            model_name='bidresponse',
            name='decision_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Decision Maker'),
        ),
        migrations.AddField(
            model_name='bid',
            name='contractors',
            field=models.ManyToManyField(to='ahp_app.Contractor'),
        ),
    ]
