# Generated by Django 2.0.2 on 2018-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteria',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
