# Generated by Django 2.0.2 on 2018-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_app', '0003_auto_20180502_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
