# Generated by Django 2.0.2 on 2018-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_app', '0004_bid_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'permissions': (('admin', 'admin'),)},
        ),
        migrations.AddField(
            model_name='bid',
            name='temp_criteria',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
