# Generated by Django 2.0.2 on 2018-05-11 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ahp_app', '0008_auto_20180511_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='bid',
            name='contractor',
            field=models.ManyToManyField(null=True, to='ahp_app.Contractor'),
        ),
        migrations.AddField(
            model_name='response',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activate Bid for Decision Makers'),
        ),
    ]
