# Generated by Django 2.0.6 on 2018-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_app', '0010_auto_20180728_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='temp_criteria',
            field=models.CharField(choices=[('FinancialStability', 'Financial Stability'), ('TechnicalCapability', 'Technical Capability'), ('PastPerformance', 'Past Performance'), ('OccupationalHS', 'Occupational Health & Safety'), ('ManagementCapability', 'Management Capability'), ('Reputation', 'Reputation'), ('Experience', 'Experience in Similar Project')], max_length=400, null=True, verbose_name='Select the appropriate criteria'),
        ),
    ]
